<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class create_listings extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $date=date('Y-m-d H:i:s');
        DB::table('listings')->insert([
            'listing_title'=>'Bondi Coffee Kitchen',
            'keywords'=>'café ,nourriture fraîche ,ambiance amicale, Menu, parking, nourriture',
            'category'=>'Manger & boire',
            'tags'=>'cafe',
            'listing_tags'=>'featured',
            'city'=>'casablanca',
            'address'=>'31 Rue Sebou Gauthier, Casablanca 20600 Maroc',
            'latitude'=>'33.589876',
            'longitude'=>'-7.631548',
            'logo'=>'/images/cafe/bondi/logo.png',
            'cover'=>'/images/cafe/bondi/photo0.jpg',
            'gallery'=>'/images/cafe/bondi/photo0.jpg, /images/cafe/bondi/photo1.jpg, /images/cafe/bondi/photo2.jpg',
            'name'=>'Justina',
            'email'=>'justina@bondicoffeektchen.com',
            'title'=>'bondicoffeekitchen',
            'tagline'=>'café ,nourriture fraîche ,ambiance amicale, Menu, parking, nourriture',
            'description'=>"<p>Bondi Coffee Kitchen est un concept de cuisine et de café de style australien au cœur de Casablanca, apportant une expérience culinaire moderne au Maroc.<br> Bondi Coffee Kitchen est un concept de boutique de restauration et de café lancé en 2015 par un couple maroco-australien qui s'est rencontré à Shanghai et a vécu dans des villes du monde entier. <br>Notre mission est de vous offrir un environnement propre et détendu où vous vous sentirez chez vous ou n'importe où dans le monde.</p>",
            'phone'=>'0651-687707',
            'monday_open'=>'09:00 AM',
            'monday_closed'=>'09:00 PM',
            'Tuesday_open'=>'09:00 AM',
            'Tuesday_closed'=>'09:00 PM',
            'Wednesday_open'=>'09:00 AM',
            'Wednesday_closed'=>'09:00 PM',
            'Thursday_open'=>'09:00 AM',
            'Thursday_closed'=>'09:00 PM',
            'Friday_open'=>'09:00 AM',
            'Friday_closed'=>'09:00 PM',
            'Saturday_open'=>'09:00 AM',
            'Saturday_closed'=>'09:00 PM',
            'Sunday_open'=>'09:00 AM',
            'Sunday_closed'=>'09:00 PM',
            'price'=>'20 MAD - 100 MAD',
            'features'=>'Climatisé ,Café bio équitable, Salades fraîches et saines, Délicieux sandwichs, Plats de pâtes copieux, Savoureuses douceurs maison',
            'status'=>'Open Now',
            'etat'=>'active',
            'created_at'=>$date,
            'video'=>'',
            'user_id'=>'2'
        ]);
        DB::table('listings')->insert([
            'listing_title'=>"L'Ardoise Gourmande",
            'keywords'=>'restaurant ,Risotto ,Cuisine Française, Parking, Lunch, nourriture',
            'category'=>'Restaurants',
            'tags'=>'Restaurant',
            'listing_tags'=>'featured',
            'city'=>'Agadir',
            'address'=>"Boulevard Hassan 2 Dans les jardins de l'atlantic hôtel, Agadir 80000 Maroc",
            'latitude'=>'33.589876',
            'longitude'=>'-7.631548',
            'logo'=>'/images/restaurant/ardoisegourmande/logo.png',
            'cover'=>'/images/restaurant/ardoisegourmande/cover.jpg',
            'gallery'=>'/images/restaurant/ardoisegourmande/1.jpg, /images/restaurant/ardoisegourmande/2.jpg, /images/restaurant/ardoisegourmande/2.jpg',
            'name'=>'',
            'email'=>'',
            'title'=>'ardoisegourmande',
            'tagline'=>'café ,nourriture fraîche ,ambiance amicale, Menu, parking, nourriture',
            'description'=>" <p>En organisant votre voyage, tenez compte de Vallee des Oiseaux et décidez où vous mangerez, en effet ce restaurant est tout près de cet endroit. D'après les commentaires des clients, la cuisine française est plutôt bonne. Si vous avez faim, venez ici pour un consommé fascinant. La plupart des visiteurs recommandent de commander un parfait savoureux.</p>
 <p>L'ardoise Gourmande est si bien placé qu'on peut y accéder par n'importe quel transport. Démarrez votre repas avec un vin délicieux. Le plus souvent, vous reviendrez à ce lieu pour essayer un café immense. Un personnel beau attend les clients tout au long de l'année. Un service fabuleux est toujours un plaisir. On vous recommande aussi cet endroit car il propose un prix abordable. Dans cet endroit, les clients peuvent apprécier une ambiance agréable et un décor luxueux. D'après les réactions des utilisateurs sur Google, ce restaurant mérite la note de 4.8.</p>
          <h5>N°2 de 1331 restaurants dans Agadir</h5>",
            'phone'=>'+212 625-996418',
            'monday_open'=>'09:00 AM',
            'monday_closed'=>'09:00 PM',
            'Tuesday_open'=>'09:00 AM',
            'Tuesday_closed'=>'09:00 PM',
            'Wednesday_open'=>'09:00 AM',
            'Wednesday_closed'=>'09:00 PM',
            'Thursday_open'=>'09:00 AM',
            'Thursday_closed'=>'09:00 PM',
            'Friday_open'=>'09:00 AM',
            'Friday_closed'=>'09:00 PM',
            'Saturday_open'=>'09:00 AM',
            'Saturday_closed'=>'09:00 PM',
            'Sunday_open'=>'09:00 AM',
            'Sunday_closed'=>'09:00 PM',
            'price'=>'99 MAD - 250 MAD',
            'features'=>'Terrasse extérieure ,Cartes de crédit acceptées, Réservation, Bières & Vins, À emporter, Bar complet, Réservations',
            'status'=>'Open Now',
            'etat'=>'en attente',
            'created_at'=>$date,
            'video'=>'',
            'user_id'=>'1'
        ]);
        DB::table('listings')->insert([
            'listing_title'=>'Mister Cook',
            'keywords'=>'snack ,tacos ,ambiance amicale, Menu, parking, nourriture,dessert',
            'category'=>'Manger & boire',
            'tags'=>'snack',
            'listing_tags'=>'',
            'city'=>'Agadir',
            'address'=>'Avenue benzidan N87 cite salam agadir maroc, Agadir 80070 Maroc',
            'latitude'=>'33.589876',
            'longitude'=>'-7.631548',
            'logo'=>'/images/snack/mistercook/logo.png',
            'cover'=>'/images/snack/mistercook/mc0.jpg',
            'gallery'=>'/images/snack/mistercook/mc0.jpg, /images/snack/mistercook/mc1.jpg, /images/snack/mistercook/mc2.jpg, /images/snack/mistercook/mc3.jpg',
            'name'=>'',
            'email'=>'administration@mistercook.ma',
            'title'=>'mistercook',
            'tagline'=>'',
            'description'=>"<p>Beaucoup de monde viennent à ce restaurant pour goûter des salades savoureuses. Ne partez pas sans avoir dégusté un parfait fascinant. Un personnel beau attend les clients tout au long de l'année. Mister cook offre un service fabuleux à ses clients. On vous recommande aussi cet endroit car il propose un prix abordable. D'après le classement de Google, ce lieu a reçu un score de 4.2.</p>",
            'phone'=>'+212 5282-24242',
            'monday_open'=>'09:00 AM',
            'monday_closed'=>'09:00 PM',
            'Tuesday_open'=>'09:00 AM',
            'Tuesday_closed'=>'09:00 PM',
            'Wednesday_open'=>'09:00 AM',
            'Wednesday_closed'=>'09:00 PM',
            'Thursday_open'=>'09:00 AM',
            'Thursday_closed'=>'09:00 PM',
            'Friday_open'=>'09:00 AM',
            'Friday_closed'=>'09:00 PM',
            'Saturday_open'=>'09:00 AM',
            'Saturday_closed'=>'09:00 PM',
            'Sunday_open'=>'09:00 AM',
            'Sunday_closed'=>'09:00 PM',
            'price'=>'20 MAD - 89 MAD',
            'features'=>'Air Conditioned ,Waiter Service, Free Wifi',
            'status'=>'Open Now',
            'etat'=>'active',
            'created_at'=>$date,
            'video'=>'',
            'user_id'=>'3'
        ]);

        DB::table('listings')->insert([
            'listing_title'=>"Agadir Quad / plage sauvage au cœur d'Agadir",
            'keywords'=>'Quad ,Loisir ,Fun, Course, plage',
            'category'=>'Activitées',
            'tags'=>'Activitées',
            'listing_tags'=>'featured',
            'city'=>'Agadir',
            'address'=>'Agadir,centre ville',
            'latitude'=>'33.589876',
            'longitude'=>'-7.631548',
            'logo'=>'/images/activités/quad/logo.png',
            'cover'=>'/images/activités/quad/photo0.jpg',
            'gallery'=>'/images/activités/quad/photo0.jpg, /images/activités/quad/photo1.jpg, /images/activités/quad/photo2.jpg',
            'name'=>'Omar',
            'email'=>'',
            'title'=>'',
            'tagline'=>'Quad ,Loisir ,Fun, Course, plage',
            'description'=>"<p>Pour découvrir nos paysages exceptionnels, les dunes de sable doré et la plage, à bord de votre propre quad / buggy, vivez une expérience passionnante à travers les paysages ruraux et le village berbère pré-saharien. Découvrez la forêt et la plage.</p><p></p><h3 class='utf_listing_headline_part margin-top-30 margin-bottom-30'>À quoi s'attendre</h3><p>L'heure de prise en charge commence à 8h30 du matin retour à 12h00 / ou / 14h00 retour vers 17h30. Transferts en navette vers et depuis votre hôtel (gratuit) le plus délicieux petit-déjeuner de style berbère. Adhérence Quads du village de LAMZAR (Ait Melloul) situé à 15 km au sud d'Agadir. Départ sur des chemins de terre, nous quittons le village de 'Lamzar'. Quelques kms plus loin nous roulons sur des pistes de sable bordées d'arganiers. Le long des pistes, vous verrez une multitude de serres sont cultivées, fruits et légumes qui alimentent les souks de la région. Demi-voyage, nous ferons une pose pour vous offrir un thé à la menthe, du pain traditionnel, de l'amlou et du miel récolté dans la région. Après cette halte dans une maison traditionnelle, nous traversons le village de Takad et des ruelles en terre puis une fête de petites pentes et de dunes de sable à plusieurs kilomètres à travers la campagne.</p><h3 class='utf_listing_headline_part margin-top-30 margin-bottom-30'>Point de départ et retour </h3><p>Hotel Riu Palace Tikida Agadir, Chemin des Dunes, Agadir 80000 Morocco </p>",
            'phone'=>'+33 1 73 43 16 25',
            'monday_open'=>'09:00 AM',
            'monday_closed'=>'09:00 PM',
            'Tuesday_open'=>'09:00 AM',
            'Tuesday_closed'=>'09:00 PM',
            'Wednesday_open'=>'09:00 AM',
            'Wednesday_closed'=>'09:00 PM',
            'Thursday_open'=>'09:00 AM',
            'Thursday_closed'=>'09:00 PM',
            'Friday_open'=>'09:00 AM',
            'Friday_closed'=>'09:00 PM',
            'Saturday_open'=>'09:00 AM',
            'Saturday_closed'=>'09:00 PM',
            'Sunday_open'=>'09:00 AM',
            'Sunday_closed'=>'09:00 PM',
            'price'=>'200 MAD - 1000 MAD',
            'features'=>'Réservation instantanée,
Stationnement gratuit sur place,
Musique live,
Accepter les cartes de crédit,
Climatisé,
Machine à café,
Parking gratuit,
Wifi gratuit,
Thé gratuit',
            'etat'=>'active',
            'status'=>'Open Now',
            'created_at'=>$date,
            'video'=>'',
            'user_id'=>'3'
        ]);

    }
}
